import { defineConfig, globalIgnores } from 'eslint/config';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';
import prettier from 'eslint-config-prettier/flat';

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Formatting is prettier's job; this turns off conflicting style rules.
  prettier,
  globalIgnores([
    // Generated by scripts/copy-draco.mjs from three's examples.
    'public/draco/**',
    '.next/**',
    // Playwright output (HTML report, traces).
    'playwright-report/**',
    'test-results/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    'src/lib/api/schema.d.ts',
  ]),
]);

export default eslintConfig;
