/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations['health_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/graph': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Graph
     * @description The walking graph as GeoJSON (nodes and edges).
     */
    get: operations['graph_graph_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/places': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Places */
    get: operations['places_places_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/nodes/nearest': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Nearest
     * @description Nearest outdoor/entrance panorama to a map click (equirectangular metres).
     */
    get: operations['nearest_nodes_nearest_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/route': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Route */
    post: operations['route_route_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/weather': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Weather */
    get: operations['weather_weather_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ErrorOut */
    ErrorOut: {
      /** Detail */
      detail: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** Health */
    Health: {
      /** Status */
      status: string;
      /** Graph Loaded */
      graph_loaded: boolean;
      /** Nodes */
      nodes: number;
      /** Edges */
      edges: number;
      /** Version */
      version: string;
    };
    /** NearestNode */
    NearestNode: {
      /** Node Id */
      node_id: string;
      /** Distance M */
      distance_m: number;
    };
    /**
     * NodeKind
     * @enum {string}
     */
    NodeKind: 'outdoor' | 'entrance' | 'indoor';
    /** PlaceOut */
    PlaceOut: {
      /**
       * Id
       * @description Node id of the representative panorama
       */
      id: string;
      /** Name Tr */
      name_tr: string;
      /** Name En */
      name_en: string;
      kind: components['schemas']['NodeKind'];
      /** Building */
      building: string | null;
      /** Node Ids */
      node_ids: string[];
    };
    /** RouteRequest */
    RouteRequest: {
      /**
       * Source
       * @description Start node id (a place id is a node id)
       */
      source: string;
      /**
       * Target
       * @description Destination node id
       */
      target: string;
      /**
       * Avoid Stairs
       * @default false
       */
      avoid_stairs: boolean;
    };
    /** RouteResponse */
    RouteResponse: {
      /** Node Ids */
      node_ids: string[];
      /** Length M */
      length_m: number;
      /** Duration S */
      duration_s: number;
      /**
       * Coordinates
       * @description [lng, lat] per node
       */
      coordinates: [number, number][];
      /** Steps */
      steps: components['schemas']['StepOut'][];
    };
    /** StepOut */
    StepOut: {
      /** Node Id */
      node_id: string;
      turn: components['schemas']['Turn'];
      /** Distance M */
      distance_m: number;
      /** Bearing Deg */
      bearing_deg: number;
      /** Text Tr */
      text_tr: string;
      /** Text En */
      text_en: string;
    };
    /**
     * Turn
     * @enum {string}
     */
    Turn:
      | 'start'
      | 'straight'
      | 'slight_left'
      | 'left'
      | 'sharp_left'
      | 'slight_right'
      | 'right'
      | 'sharp_right'
      | 'u_turn'
      | 'arrive';
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** WeatherOut */
    WeatherOut: {
      /** Observed At */
      observed_at: string;
      /** Temperature C */
      temperature_c: number;
      /**
       * Weather Code
       * @description WMO weather interpretation code
       */
      weather_code: number;
      /** Cloud Cover Pct */
      cloud_cover_pct: number;
      /** Precipitation Mm */
      precipitation_mm: number;
      /** Wind Speed Kmh */
      wind_speed_kmh: number;
      /** Wind Direction Deg */
      wind_direction_deg: number;
      /** Visibility M */
      visibility_m: number;
      /** Is Day */
      is_day: boolean;
      /** Stale */
      stale: boolean;
      /** Attribution */
      attribution: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Health'];
        };
      };
    };
  };
  graph_graph_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  places_places_get: {
    parameters: {
      query?: {
        q?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PlaceOut'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  nearest_nodes_nearest_get: {
    parameters: {
      query: {
        lat: number;
        lng: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NearestNode'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  route_route_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RouteRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RouteResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorOut'];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorOut'];
        };
      };
    };
  };
  weather_weather_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WeatherOut'];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorOut'];
        };
      };
    };
  };
}
