/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness; with a database it also runs `select 1` (keeps Supabase awake).
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Graph
         * @description The walking graph as GeoJSON (nodes and edges); ETag-cached.
         */
        get: operations["graph_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Places
         * @description Word-prefix search; with a database, typos fall back to trigrams.
         *
         *     Without ``q``: the places the map shows (open areas and entrances at
         *     measured spots); rooms and doors known only from the tour are found
         *     by searching.
         */
        get: operations["places_places_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/buildings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buildings
         * @description Building massing summary (campus blocks by default).
         */
        get: operations["buildings_buildings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/nearest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Nearest
         * @description Nearest outdoor/entrance panorama to a map click (equirectangular metres).
         *
         *     Indoor spots stand at borrowed positions and are never the answer.
         */
        get: operations["nearest_nodes_nearest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Route */
        post: operations["route_route_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/weather": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weather */
        get: operations["weather_weather_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Campus assistant; streams the Vercel AI SDK UI message protocol (v7).
         */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BuildingOut */
        BuildingOut: {
            /**
             * Id
             * @description OSM way id
             */
            id: string;
            /**
             * Code
             * @description Campus block letter, e.g. A
             */
            code: string | null;
            /** Name */
            name: string | null;
            /** Campus */
            campus: boolean;
            /** Height M */
            height_m: number;
            /**
             * Height Source
             * @description osm_levels | default | sfm
             */
            height_source: string;
            /** Lng */
            lng: number;
            /** Lat */
            lat: number;
        };
        /** ErrorOut */
        ErrorOut: {
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Graph Loaded */
            graph_loaded: boolean;
            /** Nodes */
            nodes: number;
            /** Edges */
            edges: number;
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unavailable" | "off";
            /** Version */
            version: string;
        };
        /** LocalizedText */
        LocalizedText: {
            /** Tr */
            tr: string;
            /** En */
            en: string;
        };
        /** NearestNode */
        NearestNode: {
            /** Node Id */
            node_id: string;
            /** Distance M */
            distance_m: number;
        };
        /**
         * NodeKind
         * @enum {string}
         */
        NodeKind: "outdoor" | "entrance" | "indoor";
        /** PlaceOut */
        PlaceOut: {
            /**
             * Id
             * @description Node id of the representative panorama
             */
            id: string;
            /** Name Tr */
            name_tr: string;
            /** Name En */
            name_en: string;
            kind: components["schemas"]["NodeKind"];
            /** Building */
            building: string | null;
            /** Node Ids */
            node_ids: string[];
            /**
             * Floor
             * @description Storey of a room (kind indoor), when known
             */
            floor?: number | null;
            /**
             * Area Tr
             * @description Tour area, e.g. Kimya - M Blok
             * @default
             */
            area_tr: string;
            /**
             * Area En
             * @default
             */
            area_en: string;
        };
        /** RouteRequest */
        RouteRequest: {
            /**
             * Source
             * @description Start node id (a place id is a node id)
             */
            source: string;
            /**
             * Target
             * @description Destination node id
             */
            target: string;
            /**
             * Avoid Stairs
             * @default false
             */
            avoid_stairs: boolean;
        };
        /** RouteResponse */
        RouteResponse: {
            /** Node Ids */
            node_ids: string[];
            /** Length M */
            length_m: number;
            /** Duration S */
            duration_s: number;
            /**
             * Coordinates
             * @description [lng, lat] per node; indoor spots repeat their entrance's position: draw `parts`, not this
             */
            coordinates: [
                number,
                number
            ][];
            /**
             * Parts
             * @description [lng, lat] runs the map can draw: measured nodes joined by walks outside (the line breaks at indoor spots and passages)
             */
            parts?: [
                number,
                number
            ][][];
            /** Steps */
            steps: components["schemas"]["StepOut"][];
            /**
             * Approximate
             * @description Length and duration include estimated indoor stretches
             * @default false
             */
            approximate: boolean;
        };
        /** StepOut */
        StepOut: {
            /** Node Id */
            node_id: string;
            turn: components["schemas"]["Turn"];
            /**
             * Distance M
             * @description Walked after this step (estimate indoors)
             */
            distance_m: number;
            /**
             * Bearing Deg
             * @description Compass bearing outdoors; 0 indoors
             */
            bearing_deg: number;
            /** Text Tr */
            text_tr: string;
            /** Text En */
            text_en: string;
            /**
             * Indoor
             * @description Inside a building: no compass, the distance is an estimate
             * @default false
             */
            indoor: boolean;
            /**
             * Building
             * @description Block the step is in, enters or leaves
             */
            building?: string | null;
            /**
             * Floor
             * @description Storey at the step's spot (0 = ground)
             */
            floor?: number | null;
            /**
             * Floors
             * @description Storeys climbed (+) or descended (-) by stairs
             * @default 0
             */
            floors: number;
            /** @description Indoor spot walked to (or started at) */
            place?: components["schemas"]["LocalizedText"] | null;
        };
        /**
         * Turn
         * @enum {string}
         */
        Turn: "start" | "straight" | "slight_left" | "left" | "sharp_left" | "slight_right" | "right" | "sharp_right" | "u_turn" | "arrive" | "enter" | "exit" | "go_to" | "stairs_up" | "stairs_down" | "through";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeatherOut */
        WeatherOut: {
            /** Observed At */
            observed_at: string;
            /** Temperature C */
            temperature_c: number;
            /**
             * Weather Code
             * @description WMO weather interpretation code
             */
            weather_code: number;
            /** Cloud Cover Pct */
            cloud_cover_pct: number;
            /** Precipitation Mm */
            precipitation_mm: number;
            /** Wind Speed Kmh */
            wind_speed_kmh: number;
            /** Wind Direction Deg */
            wind_direction_deg: number;
            /** Visibility M */
            visibility_m: number;
            /** Is Day */
            is_day: boolean;
            /** Stale */
            stale: boolean;
            /** Attribution */
            attribution: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    graph_graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not modified (If-None-Match) */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    places_places_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceOut"][];
                };
            };
            /** @description Not modified (If-None-Match) */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    buildings_buildings_get: {
        parameters: {
            query?: {
                campus?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    nearest_nodes_nearest_get: {
        parameters: {
            query: {
                lat: number;
                lng: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NearestNode"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_route_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    weather_weather_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeatherOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
}
